#!/usr/bin/env bash

# Set RAW WIFI TX module hostname to the specified value

set -e

NEW_NAME_OPT=$1

if [[ -z ${NEW_NAME_OPT} ]]; then
  echo "Please specify new name for this COEX charging station"
  exit 1
fi

NEW_NAME=$(echo ${NEW_NAME_OPT} | tr '[:upper:]' '[:lower:]')

echo "Setting name to ${NEW_NAME}"

echo "Backing up /etc/hostname"
cp /etc/hostname /etc/hostname.bak
echo "Writing new /etc/hostname"
echo ${NEW_NAME} > /etc/hostname

echo "Backing up /etc/hosts"
cp /etc/hosts /etc/hosts.bak
echo "Rewriting /etc/hosts with new values"
sed -i 's/127\.0\.1\.1.*/127.0.1.1\t'${NEW_NAME}'/g' /etc/hosts

echo "Done, reboot your RAW WIFI TX module to see the results"
